### ISSUE TITLE
add type="file"

### ISSUE THREAD

**Issue by MartijnR** [SEL-Columbia/pyxform#109]
The WHO project includes the development of the following feature:

_"generic file inputs for browsers that support the current media inputs. This will allow users to upload docs or pdfs e.g."_

I propose to use the following xml to do this:

``` xml
<bind nodeset="/files/my_file" type="binary"/>
.....
<upload mediatype="application/*" ref="/files/my_file">
      <label>Generic File widget</label>
</upload>
```

Surprisingly this already works in Aggregate! (and for PDFs even shows a preview)

It doesn't break ODK Collect either (which shows just a text input) which is great.

I propose to add a new type to PYXForm: `type="file"` that will create the proposed XForm output (this is more or less in line with the existing type="video", type="image" and type="audio").

@ukanga, @larryweya, @mberg 

P.S. probably needs change in ona as well to accept these files in submission?

**Comment by mberg** [comment]
@ukanga @larryweya let's prioritize this when we have the chance and teach Geoffrey and/or Roy how to make additions to PyXform

**Comment by MartijnR** [comment]
Is this available on Ona? I'd like to use it myself for a survey.

**Comment by ukanga** [comment]
We still only support `jpeg/png/mp3/wav/3gp/csv/zip` uploads, but if the
file `pd` or otherwise is within a zip file, there is no reason it should
not be uploaded if enketo does unzip files as ODK Collect does when
downloading media files. Currently this may be the only way to have files
other than the ones listed before can be uploaded within ona. The `file`
type within the xlsform, i am not sure if that is in pyxform yet.
