### ISSUE TITLE
Pyxform submission fails when space in row

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/pyxform#19]
Converting a form returns a `missing label` (or similar) error when an XLS file has a row with a space (' ') in one of the cells.

**Comment by pld** [comment]
example here, https://docs.google.com/spreadsheet/ccc?key=0AsxCVaZcfyTadFZGQUt0c1FSYndYUEJNQ2NrWmRQaWc

row 12 column 1 has a space in it.

we can add this file to a test

**Comment by nathanathan** [comment]
The error is probably coming from here:
https://github.com/modilabs/pyxform/blob/nathanathan_merge/pyxform/xls2json.py#L393

I don't know what the expected behavior should be when there is a row with no type. We could switch to throwing warnings, or throwing errors only if there is something in the name column.

**Comment by pld** [comment]
I think that makes sense.  Throw a warning and continue if there is row with only white space.

**Comment by prabhasp** [comment]
peter, closing #16 also fixed this issue for that particular file... i can't think of another case of this issue right now... but if it re-appears in the test, please re-open issue with a xls file that breaks things.
