### ISSUE TITLE
Pyxform submission fails when no hint in primary language

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/pyxform#20]
When submitting a form that has a hint in another language but not in the primary language the submission fails.

**Comment by pld** [comment]
example here, https://docs.google.com/spreadsheet/ccc?key=0AsxCVaZcfyTadHQ5ZFB0LVdTdGVrUm9SRmhCSk9lc2c

**Comment by nathanathan** [comment]
This might be resolvable by setting default_language to english in the settings sheet for the worksheet in question.

default_language does two things:
1. In the xform the default language is the language reverted to when there is no translation available for some itext element. Because of this every itext element must have a translation in the default language.
2. In the xls workbook media/labels/hints that do not have a language suffix will be treated as though their suffix is the default language. If the default language is used as a suffix for media/labels/hints, then the suffixless version will be overwritten.

Another fix would be to create blank translations in the default language for everything without a translation in the default language. But there might be a reason javarosa doesn't do that, so I think it would be a good idea to look into that further before taking this route.

**Comment by pld** [comment]
I also think (1) would resolve the issue, but it avoids the problem.  The error is in the case when a hint for the default_language (French in this example) is not included.

I think we want to assume that this form (as is) should be valid.

**Comment by prabhasp** [comment]
Right, while with labels, there should be an expectation that all the itext be available, we should not have an expectation to have a hint in any particular language; hints are by nature optional.
